name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: go build -v ./...

      - name: Debug SSH key
        env:
          PRIVATE_KEY: ${{ secrets.MONEYBOTS_EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "Key type:"
          echo "$PRIVATE_KEY" | ssh-keygen -lf -
          echo "First few lines of the key:"
          echo "$PRIVATE_KEY" | head -n 3

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.MONEYBOTS_EC2_SSH_PRIVATE_KEY }}
          HOST: moneybots.app
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh-keygen -y -f private_key > public_key
          echo "Generated public key:"
          cat public_key
          scp -i private_key -o StrictHostKeyChecking=no -v -r ./* ${USER}@${HOST}:/home/ec2-user/apps/moneybotsapi
          ssh -i private_key -o StrictHostKeyChecking=no -v ${USER}@${HOST} '
            cd /home/ec2-user/apps/moneybotsapi &&
            make deploy
          '
          rm -f private_key public_key
