name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Secrets Availability
        run: |
          echo "Checking for MONEYBOTS_EC2_SSH_PRIVATE_KEY:"
          if [ -n "${{ secrets.MONEYBOTS_EC2_SSH_PRIVATE_KEY }}" ]; then
            echo "MONEYBOTS_EC2_SSH_PRIVATE_KEY is set"
          else
            echo "MONEYBOTS_EC2_SSH_PRIVATE_KEY is not set"
          fi

          echo "Checking for GITHUB_TOKEN (should always be available):"
          if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GITHUB_TOKEN is set"
          else
            echo "GITHUB_TOKEN is not set (this is unexpected)"
          fi

      - name: Debug SSH key (if available)
        if: ${{ secrets.MONEYBOTS_EC2_SSH_PRIVATE_KEY }}
        env:
          PRIVATE_KEY: ${{ secrets.MONEYBOTS_EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "Key content check:"
          if [ -z "$PRIVATE_KEY" ]; then
            echo "The PRIVATE_KEY is empty"
          else
            echo "The PRIVATE_KEY is not empty"
            echo "Number of lines in the key:"
            echo "$PRIVATE_KEY" | wc -l
            echo "First few characters of the key (should start with '-----BEGIN'):"
            echo "$PRIVATE_KEY" | head -c 20
          fi

      - name: Echo Workflow Context
        run: |
          echo "GitHub Workflow Context:"
          echo "  Event Name: ${{ github.event_name }}"
          echo "  Repository: ${{ github.repository }}"
          echo "  Ref: ${{ github.ref }}"
          echo "  SHA: ${{ github.sha }}"
